name: Fetch NBA

on:
  schedule:
    - cron: '15 16 * * *'  # 12:15 AM PHT
    - cron: '15 17 * * *'  # 1:15 AM PHT
    - cron: '15 18 * * *'  # 2:15 AM PHT
    - cron: '15 19 * * *'  # 3:15 AM PHT
    - cron: '15 20 * * *'  # 4:15 AM PHT
    - cron: '15 21 * * *'  # 5:15 AM PHT
    - cron: '15 22 * * *'  # 6:15 AM PHT
    - cron: '15 23 * * *'  # 7:15 AM PHT
    - cron: '15 0 * * *'   # 8:15 AM PHT
    - cron: '15 1 * * *'   # 9:15 AM PHT
    - cron: '15 2 * * *'   # 10:15 AM PHT
    - cron: '15 3 * * *'   # 11:15 AM PHT
    - cron: '15 4 * * *'   # 12:15 PM PHT
    - cron: '15 5 * * *'   # 1:15 PM PHT
  workflow_dispatch: # Allows manual trigger from the Actions tab

env:
  ev_filename: nba-events.m3u8

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Manila

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download M3U8 files
        run: |
          echo "Downloading M3U8 files"
          curl -fSL "${{ secrets.NBA_EV }}" -o "${{ env.ev_filename }}"

      - name: Log the downloaded M3U8 file details
        run: |
          if [ -f "${{ env.ev_filename }}" ]; then
            echo "${{ env.ev_filename }} downloaded successfully."
            ls -lh "${{ env.ev_filename }}"
          else
            echo "Failed to download ${{ env.ev_filename }}."
          fi

      - name: Commit and push the M3U8 files (Squash Commit)
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add "${{ env.ev_filename }}"
          git commit -m "Update M3U8 files" || echo "No changes to commit"
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
